In [6]:
import numpy as np

In [7]:
my_arr = np.arange(1000000)

In [8]:
my_list = list(range(1000000))

In [9]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 21.4 ms


In [10]:
%time for _ in range(10): my_list2 = [ x * 2 for x in my_list ]

Wall time: 906 ms


#### ndarray | array 배열

In [11]:
data = np.random.randn(2, 3)

In [12]:
data

array([[ 0.11965405, -3.07749219,  0.18320124],
       [-0.13312121,  0.78673478, -0.17211613]])

In [13]:
data * 10
# ndaray에서는 한번에 처리해준다~~ 효율적! 브로드캐스팅?
# 한 번에 연산할 수 있는 블록의 크기는 컴퓨터 메모리에 따라 다름!

array([[  1.19654051, -30.77492188,   1.83201238],
       [ -1.33121213,   7.86734778,  -1.72116134]])

In [14]:
data + data

array([[ 0.2393081 , -6.15498438,  0.36640248],
       [-0.26624243,  1.57346956, -0.34423227]])

In [15]:
data.shape

(2, 3)

ndarray는 동일한 타입만 가질 수 있다.

In [16]:
data.dtype

dtype('float64')

ndim

In [17]:
data.ndim

2

In [18]:
data.shape

(2, 3)

자동적으로 생성해주는 친구들

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.empty((2, 3, 2))

array([[[7.11758894e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.12465777e-312, 1.85624672e-051]],

       [[2.88025593e+180, 1.81854776e+185],
        [6.49712373e+169, 6.87410311e-038],
        [5.05694935e-038, 1.77434132e+160]]])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

dtype

In [26]:
arr = np.array([1,2,3], dtype=np.float64)

In [27]:
arr.dtype

dtype('float64')

In [28]:
arr2 = arr.astype(np.float32)

In [29]:
arr2.dtype

dtype('float32')

Arithmetic 산술 연산

In [30]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [31]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
arr * arr
# 각각 연산이 되는게 아니라 한번에 연산됨!! vectorization


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [35]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [38]:
arr2 = np.array([[0.,4.,1.], [7.,2.,12.]])

In [39]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [40]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Broadcasting

In [41]:
# 크기가 다른 배열 간의 연산을 가능하게 해주는 것
#중요~~~

arr = np.arange(5)

In [42]:
arr

array([0, 1, 2, 3, 4])

In [43]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [62]:
# 브로드캐스팅
arr = np.random.rand(4, 3)

In [63]:
arr

array([[0.69279323, 0.65451505, 0.36115449],
       [0.13807075, 0.32128444, 0.96809865],
       [0.44531105, 0.9790896 , 0.27712831],
       [0.91155531, 0.0473016 , 0.71302564]])

In [64]:
arr.mean(0)

array([0.54693258, 0.50054767, 0.57985177])

In [65]:
demeaned = arr - arr.mean(0)

In [66]:
demeaned

array([[ 0.14586064,  0.15396738, -0.21869728],
       [-0.40886184, -0.17926323,  0.38824688],
       [-0.10162153,  0.47854193, -0.30272346],
       [ 0.36462273, -0.45324607,  0.13317387]])

In [67]:
demeaned.mean(0)

array([ 5.55111512e-17,  0.00000000e+00, -2.77555756e-17])

In [68]:
arr

array([[0.69279323, 0.65451505, 0.36115449],
       [0.13807075, 0.32128444, 0.96809865],
       [0.44531105, 0.9790896 , 0.27712831],
       [0.91155531, 0.0473016 , 0.71302564]])

In [69]:
row_means = arr.mean(1)

In [58]:
row_means.shape

(4,)

In [59]:
row_means.reshape(4,1)

array([[0.74254655],
       [0.58677749],
       [0.55263849],
       [0.43305457]])

In [60]:
demeaned = arr - row_means.reshape(4,1)

In [61]:
demeaned.mean(1)

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -1.85037171e-17])

Indexing and Slicing

In [70]:
arr = np.arange(10)

In [71]:
arr[5:8] = 12

In [72]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [74]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [75]:
arr2d[2]

array([7, 8, 9])

In [76]:
arr2d[0, 2]

3

In [77]:
arr2d[0][2]

3

3차원

In [78]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [79]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
arr3d.shape

(2, 2, 3)

In [82]:
old_value = arr3d[0].copy()

In [84]:
arr3d[0] = 42

In [85]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [86]:
arr3d[0] = old_value

In [87]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [88]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [90]:
arr2d[:2, 2]

array([3, 6])

In [91]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

Boolean Indexing

In [92]:
names = np.array(['Bob', 'Joe', 'Will','Bob','Will','Joe','Joe'])

In [93]:
data = np.random.rand(7, 4)

In [94]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [95]:
data

array([[0.78630597, 0.25277703, 0.27117716, 0.04375988],
       [0.69468493, 0.49369725, 0.93091181, 0.07354052],
       [0.40017863, 0.91344282, 0.51630183, 0.95743605],
       [0.20187996, 0.23624896, 0.25339419, 0.13550638],
       [0.24495261, 0.26713898, 0.94322354, 0.95911669],
       [0.00696051, 0.63345294, 0.20877236, 0.4966573 ],
       [0.26608439, 0.50275192, 0.20496649, 0.03245241]])

In [96]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [98]:
data[names == 'Bob']

# True인 인덱스 값만 뽑아져 나옴

array([[0.78630597, 0.25277703, 0.27117716, 0.04375988],
       [0.20187996, 0.23624896, 0.25339419, 0.13550638]])

In [99]:
data[~(names == 'Bob')]

array([[0.69468493, 0.49369725, 0.93091181, 0.07354052],
       [0.40017863, 0.91344282, 0.51630183, 0.95743605],
       [0.24495261, 0.26713898, 0.94322354, 0.95911669],
       [0.00696051, 0.63345294, 0.20877236, 0.4966573 ],
       [0.26608439, 0.50275192, 0.20496649, 0.03245241]])

In [101]:
cond = names == 'Bob'

In [102]:
data[~cond]

array([[0.69468493, 0.49369725, 0.93091181, 0.07354052],
       [0.40017863, 0.91344282, 0.51630183, 0.95743605],
       [0.24495261, 0.26713898, 0.94322354, 0.95911669],
       [0.00696051, 0.63345294, 0.20877236, 0.4966573 ],
       [0.26608439, 0.50275192, 0.20496649, 0.03245241]])

In [103]:
mask = (names == 'Bob') | (names == 'Will')

In [104]:
mask

array([ True, False,  True,  True,  True, False, False])

In [106]:
arr = np.empty((8,4))

In [108]:
for i in range(8):
    arr[i] = [i]

In [109]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [110]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [114]:
arr = np.arange(32).reshape((8, 4))

In [115]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [116]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [120]:
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [121]:
# transposing 2차원 배열에서만 사용

arr = np.random.rand(6, 3)

In [123]:
np.dot(arr.T, arr)

array([[2.48124648, 1.46602542, 2.15497995],
       [1.46602542, 1.93807435, 2.14569705],
       [2.15497995, 2.14569705, 3.5031941 ]])

In [125]:
arr = np.arange(16).reshape((2, 2, 4))

In [126]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [127]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

### 7 넘파이 2

In [128]:
arr = np.arange(10)